apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources-service-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: resources-service
  template:
    metadata:
      labels:
        app: resources-service
    spec:
      containers:
        - name: resources-service
          image: ekirkilevics/resources-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: resources-service-config
          env:
            - name: RESOURCES_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: resources-db-secret
                  key: username
            - name: RESOURCES_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: resources-db-secret
                  key: password
          startupProbe:
            tcpSocket:
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8080
            periodSeconds: 5
            failureThreshold: 3
