apiVersion: v1
kind: PersistentVolume
metadata:
  name: songs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/songs-storage
    type: DirectoryOrCreate
