apiVersion: v1
kind: ConfigMap
metadata:
  name: resources-db-init
  namespace: k8s-program
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS resources (
        id   SERIAL PRIMARY KEY,
        blob BYTEA
    );
