apiVersion: v1
kind: Secret
metadata:
  name: resources-db-secret
  namespace: k8s-program
type: Opaque
stringData:
  username: postgres
  password: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: songs-db-secret
  namespace: k8s-program
type: Opaque
stringData:
  username: postgres
  password: postgres
