apiVersion: v1
kind: Service
metadata:
  name: songs-service
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: songs-service
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081