apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: songs-db
  namespace: k8s-program
spec:
  serviceName: songs-db
  replicas: 1
  selector:
    matchLabels:
      app: songs-db
  template:
    metadata:
      labels:
        app: songs-db
    spec:
      containers:
        - name: songs-db
          image: postgres:17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: songs-db-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: songs-db-secret
                  key: password
          startupProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            failureThreshold: 20
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            periodSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: songs-db-storage
              mountPath: /var/lib/postgresql/data
            - name: songs-db-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: songs-db-init
          configMap:
            name: songs-db-init
  volumeClaimTemplates:
    - metadata:
        name: songs-db-storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
